worker_processes	auto;
error_log	stderr notice;
pid			/run/nginx.pid;


events {
	worker_connections	1024;
}


http {
	access_log	/dev/stdout;

	include			/etc/nginx/mime.types;
	default_type	application/octet-stream;

	sendfile	on;
	tcp_nopush	on;

	keepalive_timeout	65;
	http2	on;

	ssl_certificate		/run/secrets/cert.pem;
	ssl_certificate_key	/run/secrets/key.pem;
	ssl_protocols	TLSv1.3;
	ssl_ecdh_curve	X25519:prime256v1:secp384r1;
	ssl_prefer_server_ciphers	off;


	server {
		listen	443 ssl;

		root	/usr/share/nginx/html;
		index	index.html;


		location / {
			try_files	/index.html =404;
		}

		location /api {
			proxy_cache_bypass	$http_upgrade;
			proxy_http_version	1.1;
			proxy_read_timeout	24h;
			proxy_set_header	Connection 'upgrade';
			proxy_set_header	Host $host;
			proxy_set_header	Upgrade $http_upgrade;
			proxy_set_header	X-Forwarded-For $proxy_add_x_forwarded_for;
			proxy_set_header	X-Forwarded-Proto $scheme;
			proxy_set_header	X-Real-IP $remote_addr;

			proxy_pass	http://app:3000/api;

			location = /api/account/avatar {
				client_max_body_size	64M;
				proxy_pass	http://app:3000/api/account/avatar;
			}
		}

		location ~ ^/(assets|favicon\.ico|static) {
			try_files	$uri =404;
		}
	}
}
