import {FastifyInstance, FastifyRequest} from 'fastify';
import {randomBytes} from 'node:crypto';

const {NODE_ENV} = process.env;
let {JWT_SECRET} = process.env;

export default function (server: FastifyInstance) {
  if (!JWT_SECRET) {
    const message = 'JWT_SECRET environment variable is not set';

    if (NODE_ENV === 'development') {
      JWT_SECRET = randomBytes(32).toString('base64');
      server.log.warn(`${message}, using autogenerated key: ${JWT_SECRET}`);
    } else throw new Error(message);
  }

  void server.register(import('@fastify/jwt'), {secret: JWT_SECRET});

  server.decorate('authenticate', async (request: FastifyRequest) => {
    await request.jwtVerify();
  });
}
