import {FastifyPluginAsync} from 'fastify';
import {randomBytes} from 'node:crypto';
import fp from 'fastify-plugin';

let {COOKIE_SECRET} = process.env;

const plugin: FastifyPluginAsync = async server => {
  if (!COOKIE_SECRET) {
    const message = 'COOKIE_SECRET environment variable is not set';

    if (server.dev) {
      COOKIE_SECRET = randomBytes(32).toString('base64');
      server.log.warn(`${message}, using autogenerated key: ${COOKIE_SECRET}`);
    } else throw new Error(message);
  }

  await server.register(import('@fastify/cookie'), {
    secret: COOKIE_SECRET,
    parseOptions: {
      maxAge: 30 * 24 * 60 * 60, // 30 days
      httpOnly: true,
      sameSite: 'strict',
      secure: true,
    },
  });
};

export default fp(plugin);
