import {FastifyPluginAsync} from 'fastify';
import SQL from 'sql-template-strings';
import {randomBytes} from 'node:crypto';

const {JWT_EXPIRES_IN} = process.env;
let {JWT_SECRET} = process.env;

const plugin: FastifyPluginAsync = async server => {
  if (!JWT_SECRET) {
    const message = 'JWT_SECRET environment variable is not set';

    if (server.prod) throw new Error(message);

    JWT_SECRET = randomBytes(32).toString('base64');
    server.log.warn(`${message}, using autogenerated key: ${JWT_SECRET}`);
  }

  server.decorateRequest('session', null);

  await server.register(import('@fastify/jwt'), {
    secret: JWT_SECRET,
    cookie: {
      cookieName: 'refreshToken',
      signed: false,
    },
    sign: {
      expiresIn: JWT_EXPIRES_IN && server.dev ? JWT_EXPIRES_IN : '15m',
    },
    async trusted(request, decodedToken) {
      const {id: userID, type} = decodedToken;
      const query = SQL`
        SELECT id
        FROM sessions
      `;
      let token;

      if (type === 'access') {
        token = request.headers.authorization?.split(' ')[1];
        query.append(SQL`
          WHERE user_id = ${userID} AND access_token = ${token}
        `);
      } else if (type === 'refresh') {
        token = request.cookies.refreshToken;
        query.append(SQL`
          WHERE user_id = ${userID} AND refresh_token = ${token}
        `);
      }

      if (!token) return false;

      const session = await server.db.get(query);
      if (!session) return false;

      request.session = session.id;
      return true;
    },
  });
};

export default plugin;
