import {FastifyPluginAsync} from 'fastify';
import {randomBytes} from 'node:crypto';
import fp from 'fastify-plugin';

let {JWT_SECRET} = process.env;

const plugin: FastifyPluginAsync = async server => {
  if (!JWT_SECRET) {
    const message = 'JWT_SECRET environment variable is not set';

    if (server.dev) {
      JWT_SECRET = randomBytes(32).toString('base64');
      server.log.warn(`${message}, using autogenerated key: ${JWT_SECRET}`);
    } else throw new Error(message);
  }

  void server.register(import('@fastify/jwt'), {secret: JWT_SECRET});

  server.decorate('authenticate', async request => {
    await request.jwtVerify();
  });
};

export default fp(plugin);
