import {FastifyPluginAsync} from 'fastify';
import SQL from 'sql-template-strings';
import fp from 'fastify-plugin';
import {randomBytes} from 'node:crypto';

let {JWT_SECRET} = process.env;

const plugin: FastifyPluginAsync = async server => {
  if (!JWT_SECRET) {
    const message = 'JWT_SECRET environment variable is not set';

    if (server.dev) {
      JWT_SECRET = randomBytes(32).toString('base64');
      server.log.warn(`${message}, using autogenerated key: ${JWT_SECRET}`);
    } else throw new Error(message);
  }

  await server.register(import('@fastify/jwt'), {
    secret: JWT_SECRET,
    cookie: {
      cookieName: 'refreshToken',
      signed: false,
    },
    sign: {
      expiresIn: '10m',
    },
    async trusted(request, decodedToken) {
      if (decodedToken.type === 'access') {
        const {authorization} = request.headers;
        if (!authorization) return false;

        const token = authorization.split(' ')[1];
        if (!token) return false;

        return (
          (await server.db.get(
            SQL`SELECT user_id FROM tokens WHERE user_id = ${decodedToken.id} AND access = ${token}`,
          )) !== undefined
        );
      }

      if (decodedToken.type === 'refresh') {
        const token = request.cookies.refreshToken;
        if (!token) return false;

        return (
          (await server.db.get(
            SQL`SELECT user_id FROM tokens WHERE user_id = ${decodedToken.id} AND refresh = ${token}`,
          )) !== undefined
        );
      }

      return false;
    },
  });

  server.decorate('authenticate', async request => {
    await request.jwtVerify();
  });

  server.decorate('authenticateRefresh', async request => {
    await request.jwtVerify({onlyCookie: true});
  });
};

export default fp(plugin);
